### ISSUE TITLE
If site_url() contains a path, the plugin replaces too much

### ISSUE THREAD

**Issue by florianendrich** [yasglobal/make-paths-relative#10]
Hi,

I've encountered an issue with path replacements in WordPress. When the site_url() is set to http://10.10.10.10/blog, all absolute paths are incorrectly being replaced. For example:

Current behavior:

URL `http://10.10.10.10/blog/wp-content/uploads/test.jpg` is being replaced with `/wp-content/uploads/test.jpg`.

Desired behavior:
URL `http://10.10.10.10/blog/wp-content/uploads/test.jpg` should be replaced with `/blog/wp-content/uploads/test.jpg`.

Current Workaround:
We've implemented a temporary fix using a dirty hack by substituting site_url() with $_SERVER['HTTP_HOST']. The current code looks like this:

`$host_name = $_SERVER['HTTP_HOST']; // Temporary hack`

Instead of:
`$host_name = site_url();`

Request:
I'm looking for a more robust and cleaner solution to ensure that paths are replaced correctly without resorting to this hack. Any guidance or suggestions would be greatly appreciated.

Thank you!

**Comment by samiahmedsiddiqui** [comment]
@florianendrich A new version of the plugin is available with improved functionality. To take advantage of these improvements, please update to the latest version.  

Heads up: The update includes some changes to the plugin's settings.  Be sure to update your settings and define `10.10.10.10` manually in the site addresses to resolve your issue.

**Comment by florianendrich** [comment]
Setting the `$host_name` to 10.10.10.10 does not solve the issue for me as it is not a fixed value.

Our Installations serves many clients who are connected via different subnets. So we have something like this in the wp-config.php:

```
if ($_SERVER['HTTP_HOST'] == '10.10.10.10') {
    define('WP_SITEURL', 'http://10.10.10.10/blog');
    define('WP_HOME',    'http://10.10.10.10/blog');
} else if (....) {
    define('WP_SITEURL', 'http://10.11.11.11/blog');
    define('WP_HOME',    'http://10.11.11.11/blog');
}
```

So using `$_SERVER['HTTP_HOST'];` solves the issue while `site_url();` returns `http://X.X.X.X/blog` and setting `10.10.10.10` is only suitable for one client.

Either allowing multiple values or maybe let the user enter / or choose `$_SERVER['HTTP_HOST']` would help.

**Comment by samiahmedsiddiqui** [comment]
@florianendrich In the latest version of the plugin, you are allowed to enter multiple values so it can resolves your issue. Please download the latest version from here.
https://github.com/yasglobal/make-paths-relative/releases

**Comment by florianendrich** [comment]
the input field is now handled as array which fixes the issue for me.
