### ISSUE TITLE
Make available from Packagist

### ISSUE THREAD

**Issue by joelambert** [yasglobal/make-paths-relative#12]
It appears the plugin has been removed from the WordPress plugin directory and has therefore stopped working with WPackagist.

As you have a well defined `composer.json` and suitable tags in the GitHub repo could you please submit it to https://packagist.org so that we can continue to install via Composer please?

**Comment by samiahmedsiddiqui** [comment]
@joelambert Yes, plugin has removed from the WordPress plugins directory and I have requested earlier today to WordPress Plugin team to open it again.

Meanwhile, I have submitted the required on packagist and here is the direct URL.
https://packagist.org/packages/yasglobal/make-paths-relative

**Comment by samiahmedsiddiqui** [comment]
@joelambert Please let me know if there is anything else for me to do,

**Comment by joelambert** [comment]
@samiahmedsiddiqui amazing, thanks. Out of interest, only v2 is showing up in Packagist, is this deliberate? It would be great if we could still access older versions so that we can upgrade at a more manageable time.

**Comment by samiahmedsiddiqui** [comment]
@joelambert It is not deliberate. Actually, I added `package.json` in v2 and that seems to be a reason of not showing older versions in packagist.

**Comment by joelambert** [comment]
Ok, that's odd. From my experience after hooking it up to the GitHub repo it should just pickup all your tags and then auto update the packagist repository too.
