### ISSUE TITLE
Make Paths Relative conflicts with Yoast Sitemap in last version of both plugins

### ISSUE THREAD

**Issue by albanleandri** [yasglobal/make-paths-relative#2]
I am using the Pantheon Workflow (Dev > Test > Live) and Make Paths Relative (MPR) is super useful to keep links to images, and urls relative from an environment to another.
Recently I found an issue, however.
When MPR is activated for all content types, then the Sitemaps generated by Yoast plugin will contain only "relative" paths which is a serious issue for SEO. Indeed Google guidance for sitemaps recomments full absolute URLs, and not relative URLs.
I saw that a [previous release](https://github.com/yasglobal/make-paths-relative/releases/tag/v0.5.1) supposedly tackled this issue, but the benefit is not visible in the latest release of MPR.

Replication steps :
- Install Yoast, activate it and enable Sitemap
- Install MPR, activate it, and check all to make paths relative
- Go to your sitemaps URL

Actual result : Sitemaps urls are relative
Expected result : Sitemaps urls should be absolute

**Comment by albanleandri** [comment]
Hi @yasglobal, here's an issue that requires your attention. Thanks a lot :)

**Comment by albanleandri** [comment]
Hi @yasglobal, just trying to follow-up, if you can advise for a workaround?

**Comment by samiahmedsiddiqui** [comment]
@AlbanL74fr Sorry about the issue and thank you for pointing this out.

I have fixed this issue but it appears again due to the recent change of Yoast SEO. I have fixed the issue and will release it at some time today.

**Comment by samiahmedsiddiqui** [comment]
@AlbanL74fr `v1.1.2` is released. You can update the version and it will fix your sitemap issue.


Don't forget to provide us a feedback 😄

**Comment by albanleandri** [comment]
Hi @yasglobal, thanks, I have tested it according to the steps outlined in my issue description, and the bug seems to be fixed.
