### ISSUE TITLE
MPR conflicts with OneSignal plugin : images and links in web push notification are relative (and break)

### ISSUE THREAD

**Issue by albanleandri** [yasglobal/make-paths-relative#3]
When Make Paths Relative is active and image paths are set to relative, then OneSignal web push notification have relative paths for images, and image break.
Tested with latest versions of MPR and OS.

**Comment by samiahmedsiddiqui** [comment]
@AlbanL74fr Please sent the OneSignal plugin to me so I can test. Also, is there any settings in the plugin? If yes, so, please provide me the screenshot of it.

**Comment by albanleandri** [comment]
OK, thanks for replying. I will try to give you as many details as possible here.

First, here's the link to the plugin OneSignal Push: https://wordpress.org/plugins/onesignal-free-web-push-notifications/
If you create an account here (free) : https://app.onesignal.com/
It will help you test, so you will have Rest API Key, and AppID

Second, see below how paths are shown in OneSignal dashboard, for the web push with broken images. You notive that all of them are "relative" when they should be absolute, for the asset to be found
![image](https://user-images.githubusercontent.com/23435414/63763906-db177f80-c8ef-11e9-858c-ca873e745881.png)

Here's another example where the image paths have been set to "Absolute" again, but where "post" are still "relative":

![image](https://user-images.githubusercontent.com/23435414/63771739-ec698780-c901-11e9-8acb-396022150612.png)


I haven't tested but I guess those links won't take me anywere as there is no hostname.

Now, here's the settings I am using for OneSignal Push :

![image](https://user-images.githubusercontent.com/23435414/63764338-cab3d480-c8f0-11e9-9859-99c8f50eb0dd.png)


And the ones I have been using in MPR to fix the issue :

![image](https://user-images.githubusercontent.com/23435414/63771857-263a8e00-c902-11e9-98c8-bc1cc5986627.png)


As you can see I had to make image paths and post paths "absolute" again, in order to avoid 404 and for my web pushs to show images properly or links relative.

I am not sure if this is possible in Wordpress, but do you think we could add a list of "Ignore these plugins", so exception rules "by plugins", which means that MPR would not try making paths "relative" when entities (image, posts, etc..) are being handled by the plugins listed in the list in the settings of MRP.

Thanks a lot :)

**Comment by samiahmedsiddiqui** [comment]
> I am not sure if this is possible in Wordpress, but do you think we could add a list of "Ignore these plugins", so exception rules "by plugins", which means that MPR would not try making paths "relative" when entities (image, posts, etc..) are being handled by the plugins listed in the list in the settings of MRP.

There is no such thing in WordPress.

**Comment by samiahmedsiddiqui** [comment]
@AlbanL74fr I have created an account on OneSignal and made configuration but I am not seeing the data result as you have shown in the screenshot. How can I navigate to that page?

**Comment by albanleandri** [comment]
@yasglobal After you send at least one webpush notification, there will be data in the
Delivery menu, in the dashboard (not the plugin, but onesignal site) so you can go and pick the webpush you sent and see the
details. All will be listed there, including url of assets used, title,
content, links, etc...

Btw, I found this ::
https://documentation.onesignal.com/docs/web-push-wordpress-faq#section-customizing-wordpress-plugin-behavior
There is a section "onesignal_send_notification Filter" : Called after all
the notification creation parameters have been determined, and right before
the notification is actually sent.

Maybe it can help.

**Comment by albanleandri** [comment]
@yasglobal Hi, any news about this issue?

**Comment by samiahmedsiddiqui** [comment]
@albanleandri Previously, I tried but I was not able to generate this issue. so not made any changes for this. If you can generate this issue somewhere and providing me the access so please let me know.
