### ISSUE TITLE
Option for folder

### ISSUE THREAD

**Issue by illycz** [yasglobal/make-paths-relative#4]
Your plugin looks promising.
But I need add folder to final url.

For example from domainA.com -> domainB.com/folder/

Is it possible?

Thanks

**Comment by illycz** [comment]
I solved it within your filter:

```
function mytheme_paths_relative( $link ) {
	$link = '/folder' . $link;

	return $link;
  }
add_filter( 'paths_relative', 'mytheme_paths_relative' );
```

One issue is, that sitemap.xml is not generated on new address, but I think it's not your plugin problem...
But If you have any suggestions I will appreciate.

Thanks

**Comment by JoaquinFernandez** [comment]
Thank you for the snippet @illycz! It works like a charm

**Comment by samiahmedsiddiqui** [comment]
> One issue is, that sitemap.xml is not generated on new address, but I think it's not your plugin problem...

@illycz Do you still have this issue or is it fixed? If it is fixed can you share how you actually fixed it so it helps other users if they will have a similar issue.

**Comment by illycz** [comment]
@samiahmedsiddiqui Sorry, I finally uninstalled this plugin because project expectations changed.

**Comment by samiahmedsiddiqui** [comment]
@illycz No worries, thank you for your reply.
